import type { Product } from '../types';

export const MOCK_MEDICINES: Product[] = [
    {
        id: 'med-1',
        name: 'Amoxicillin 500mg',
        category: 'medicine',
        price: 10.60,
        originalPrice: 12.50,
        image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
        description: 'Antibiotic for bacterial infections',
        manufacturer: 'PharmaGlobal Ltd',
        prescriptionRequired: true,
        discount: 15,
    },
    {
        id: 'med-2',
        name: 'Omega 3 Fish Oil',
        category: 'medicine',
        price: 18.20,
        image: 'https://images.unsplash.com/photo-1550572017-4a6e8c4e8a6c?w=400',
        description: 'Essential fatty acids supplement',
        manufacturer: 'NaturePure',
        prescriptionRequired: false,
    },
    {
        id: 'med-3',
        name: 'Paracetamol 650mg',
        category: 'medicine',
        price: 4.50,
        image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400',
        description: 'Pain relief and fever reducer',
        manufacturer: 'CarePlus Brands',
        prescriptionRequired: false,
    },
    {
        id: 'med-4',
        name: 'Multivitamin Daily',
        category: 'medicine',
        price: 15.40,
        originalPrice: 22.00,
        image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=400',
        description: 'Complete daily vitamin supplement',
        manufacturer: 'HealthFirst',
        prescriptionRequired: false,
        discount: 30,
    },
    {
        id: 'med-5',
        name: 'Digital Thermometer',
        category: 'medicine',
        price: 12.00,
        image: 'https://images.unsplash.com/photo-1584515933487-779824d29309?w=400',
        description: 'Accurate digital temperature measurement',
        manufacturer: 'TechHealth',
        prescriptionRequired: false,
    },
    {
        id: 'med-6',
        name: 'Vitamin D3 5000 IU',
        category: 'medicine',
        price: 14.99,
        image: 'https://images.unsplash.com/photo-1550572017-4a6e8c4e8a6c?w=400',
        description: 'Bone health and immunity support',
        manufacturer: 'VitaLife',
        prescriptionRequired: false,
    },
];

export const MOCK_LAB_TESTS: Product[] = [
    {
        id: 'lab-1',
        name: 'Comprehensive Full Body Checkup',
        category: 'labtest',
        price: 79.00,
        originalPrice: 120.00,
        image: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?w=400',
        description: 'Complete evaluation including liver, kidney, thyroid, heart and more',
        parameters: 82,
        discount: 34,
    },
    {
        id: 'lab-2',
        name: 'Diabetes Screening Profile',
        category: 'labtest',
        price: 29.00,
        originalPrice: 45.00,
        image: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400',
        description: 'Essential screening for HbA1c, fasting blood sugar, and insulin resistance',
        parameters: 12,
        discount: 35,
    },
    {
        id: 'lab-3',
        name: 'Advanced Thyroid Profile',
        category: 'labtest',
        price: 49.00,
        originalPrice: 60.00,
        image: 'https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=400',
        description: 'Complete thyroid panel including T3, T4, TSH, and anti-TPO antibodies',
        parameters: 6,
        discount: 18,
    },
    {
        id: 'lab-4',
        name: 'Vital Vitamin Combo',
        category: 'labtest',
        price: 35.00,
        originalPrice: 55.00,
        image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400',
        description: 'Check your Vitamin D and B12 levels for energy and bone health',
        parameters: 2,
        discount: 36,
    },
    {
        id: 'lab-5',
        name: 'Healthy Heart Advanced',
        category: 'labtest',
        price: 99.00,
        originalPrice: 140.00,
        image: 'https://images.unsplash.com/photo-1628348068343-c6a848d2b6dd?w=400',
        description: 'Advanced lipid profile, hs-CRP, and homocysteine for heart risk assessment',
        parameters: 22,
        discount: 29,
    },
    {
        id: 'lab-6',
        name: 'Women Health Super Plus',
        category: 'labtest',
        price: 85.00,
        originalPrice: 110.00,
        image: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400',
        description: 'Tailored screening including PCOD, Iron studies, and hormonal balance',
        parameters: 64,
        discount: 22,
    },
];
